### ISSUE TITLE
java.lang.IllegalStateException Fragment's view can't be accessed. Fragment isn't added

### ISSUE THREAD

**Issue by DmitryLukky** [androidbroadcast/ViewBindingPropertyDelegate#100]
Hello, version 1.5.6, crashlytics reports new crashes:

`Fatal Exception: java.lang.IllegalStateException: Fragment's view can't be accessed. Fragment isn't added
       at by.kirich1409.viewbindingdelegate.LifecycleViewBindingProperty.getValue(ViewBindingProperty.kt:87)
       at by.kirich1409.viewbindingdelegate.FragmentViewBindingProperty.getValue(FragmentViewBindings.kt:63)
       at by.kirich1409.viewbindingdelegate.FragmentViewBindingProperty.getValue(FragmentViewBindings.kt:52)`

In fragment i declare like this: `private val binding by viewBinding(FragmentFirstBinding::bind)`

![image](https://user-images.githubusercontent.com/57831537/159237863-30188f63-ce16-4186-a7ba-516f82dcb0b2.png)

**Comment by kirich1409** [comment]
The issue has full informatio in crash log. You try to access viewbinding when Fragment isn't added and has no view. Check state of Fragment before update views
