### ISSUE TITLE
Android Studio Dolphin | 2021.3.1 does not show layout preview

### ISSUE THREAD

**Issue by kongnanlive** [androidbroadcast/ViewBindingPropertyDelegate#108]
java.lang.NullPointerException: Missing required view with ID: com.danatech.component.widget:id/ibv_right_more
	at com.danatech.component.widget.databinding.CommonTitleBinding.bind(CommonTitleBinding.java:132)
	at com.danatech.component.widget.CommonTitleBar.<init>(CommonTitleBar.kt:27)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:351)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:200)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:161)
	at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadView(LayoutlibCallbackImpl.java:294)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:417)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:428)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:332)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:663)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:505)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:359)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:436)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:121)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:717)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$9(RenderTask.java:873)
	at com.android.tools.idea.rendering.RenderExecutor$runAsyncActionWithTimeout$3.run(RenderExecutor.kt:192)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

``` kotlin
class CommonTitleBar : FrameLayout {

    private val binding by viewBinding(CommonTitleBinding::bind)

    init {
        binding.ivTitleClose.setOnClickListener {
        }
    }
}
```

Removing ` isInEditMode -> EagerViewBindingProperty(vbFactory(this)) ` solved it

**Comment by kirich1409** [comment]
Can you provide example project where the issue is reproducible?

**Comment by kongnanlive** [comment]
``` kotlin

@file:Suppress("unused")

package by.kirich1409.viewbindingdelegate.sample.view.noreflection

import android.content.Context
import android.util.AttributeSet
import android.widget.LinearLayout
import by.kirich1409.viewbindingdelegate.sample.R
import by.kirich1409.viewbindingdelegate.sample.databinding.ViewProfileBinding
import by.kirich1409.viewbindingdelegate.viewBinding

class ProfileView @JvmOverloads constructor(
    context: Context, attrs: AttributeSet? = null
) : LinearLayout(context, attrs) {

    init {
        inflate(context, R.layout.view_profile, this) // Just write it here
    }

    private val viewBinding by viewBinding(ViewProfileBinding::bind)

    init {
//        inflate(context, R.layout.view_profile, this) // cannot be written in this location
        viewBinding.name.text = "Hello World"
    }
}

```

After testing I solved this bug
