### ISSUE TITLE
Fatal Exception: not associated with a fragment manager.

### ISSUE THREAD

**Issue by renjinlong** [androidbroadcast/ViewBindingPropertyDelegate#89]
com.github.kirich1409:viewbindingpropertydelegate-noreflection:1.5.0-beta01

java.lang.IllegalStateException: Fragment jk0{f8c8674} (7e1096ef-ea26-4448-9600-723d9e44047a) not associated with a fragment manager.
	at androidx.fragment.app.Fragment.getParentFragmentManager(app:2)
	at by.kirich1409.viewbindingdelegate.FragmentViewBindingProperty.registerFragmentLifecycleCallbacks(app:3)
	at by.kirich1409.viewbindingdelegate.FragmentViewBindingProperty.getValue(app:4)
	at by.kirich1409.viewbindingdelegate.FragmentViewBindingProperty.getValue(app:3)
	at net.qihoo.honghu.ui.fragment.VpContentFragment.getMBinding(app)
	at net.qihoo.honghu.ui.fragment.VpContentFragment.access$getMBinding$p(app:1)
	at net.qihoo.honghu.ui.fragment.VpContentFragment$initObserver$5$1$1.run(app:1)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:159)
	at android.app.ActivityThread.main(ActivityThread.java:6385)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1096)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)

**Comment by AdamGrzybkowski** [comment]
I see the same issue with 1.5.0-beta01, was this fixed in 1.5.2?

**Comment by kirich1409** [comment]
It's look like you try to get ViewBinding instance for a Fragment that isn't added
